# The URL the site will be built for
base_url = "https://devpi.de"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "serene"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
avatar = "img/avatar.webp"
name = "Julius Lehmann"
id = "lehmanju"
bio = "Computer Scientist B.Sc."
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/lehmanju" },
    { name = "Email", icon = "email", url = "mailto:julius@devpi.de" },
]

homepage_layout = "about"             # "about" | "list"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    # { name = "about", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true                     # Whether to display your id on homepage
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2023 <your-name>"
footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
